### ISSUE TITLE
TODO before PR

### ISSUE THREAD

**Issue by discordier** [sheeep/core-bundle#1]
Change `contao-components/contao`
-----------------------------------------------
`js/core.js`:
```diff
diff --git a/js/core.js b/js/core.js
index 14242c8..cf4bb56 100644
--- a/js/core.js
+++ b/js/core.js
@@ -38,11 +38,11 @@ var AjaxRequest =
                        if (parent.hasClass('node-collapsed')) {
                                item.setStyle('display', null);
                                parent.removeClass('node-collapsed').addClass('node-expanded');
-                               new Request.Contao().post({'action':'toggleNavigation', 'id':id, 'state':1, 'REQUEST_TOKEN':Contao.request_t
+                               new Request.Contao({'url': el.href}).post({'action':'toggleNavigation', 'id':id, 'state':1, 'REQUEST_TOKEN':
                        } else {
                                item.setStyle('display', 'none');
                                parent.removeClass('node-expanded').addClass('node-collapsed');
-                               new Request.Contao().post({'action':'toggleNavigation', 'id':id, 'state':0, 'REQUEST_TOKEN':Contao.request_t
+                               new Request.Contao({'url': el.href}).post({'action':'toggleNavigation', 'id':id, 'state':0, 'REQUEST_TOKEN':
                        }
                        return false;
                }
```

Drink beer!
-----------------
... plenty of beer!

**Comment by discordier** [comment]
- [ ] Translation handling using delegating twig translation manager (Codename: Quasimodo).
- [ ] Permission voter(?)
- [ ] Show controllers in Backend user editing for "Has access" checkboxes.
- [ ] Missing tests
- [ ] Code cleanup (remove unused parts from Legacy Contao code)
    - [ ] Remove Ajax handler for `toggleNavigation`
    - [ ] PHPDoc
    - [ ] File headers (including `@author`)
    - [ ] Coding style (ensure yoda conditions in refactored code)
